# Set WATCH_NAMESPACE to "" in the deployment to provide cluster-wide install
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesJson6902:
  - target:
      group: apps
      version: v1
      name: controller-manager
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env/0/valueFrom
      - op: add
        path: /spec/template/spec/containers/0/env/0/value
        value: ""
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: manager-role
    patch: |-
      - op: replace
        path: /metadata/name
        value: cass-operator-manager-crrole
      - op: replace
        path: /kind
        value: ClusterRole
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: manager-rolebinding
    patch: |-
      - op: replace
        path: /roleRef/kind
        value: ClusterRole
      - op: replace
        path: /roleRef/name
        value: cass-operator-manager-crrole
      - op: replace
        path: /subjects/0/name
        value: cass-operator-controller-manager
      - op: replace
        path: /kind
        value: ClusterRoleBinding
