apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8ssandra-operator

resources:
  - github.com/k8ssandra/cass-operator/config/deployments/default?ref=211eac97af729b03d8551ebccb88c6e7e376c567
  - ../../default
