// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: pkg/medusa/medusa.proto

package medusa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusType int32

const (
	StatusType_IN_PROGRESS StatusType = 0
	StatusType_SUCCESS     StatusType = 1
	StatusType_FAILED      StatusType = 2
	StatusType_UNKNOWN     StatusType = 3
)

// Enum value maps for StatusType.
var (
	StatusType_name = map[int32]string{
		0: "IN_PROGRESS",
		1: "SUCCESS",
		2: "FAILED",
		3: "UNKNOWN",
	}
	StatusType_value = map[string]int32{
		"IN_PROGRESS": 0,
		"SUCCESS":     1,
		"FAILED":      2,
		"UNKNOWN":     3,
	}
)

func (x StatusType) Enum() *StatusType {
	p := new(StatusType)
	*p = x
	return p
}

func (x StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_medusa_medusa_proto_enumTypes[0].Descriptor()
}

func (StatusType) Type() protoreflect.EnumType {
	return &file_pkg_medusa_medusa_proto_enumTypes[0]
}

func (x StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusType.Descriptor instead.
func (StatusType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{0}
}

type BackupRequest_Mode int32

const (
	BackupRequest_DIFFERENTIAL BackupRequest_Mode = 0
	BackupRequest_FULL         BackupRequest_Mode = 1
)

// Enum value maps for BackupRequest_Mode.
var (
	BackupRequest_Mode_name = map[int32]string{
		0: "DIFFERENTIAL",
		1: "FULL",
	}
	BackupRequest_Mode_value = map[string]int32{
		"DIFFERENTIAL": 0,
		"FULL":         1,
	}
)

func (x BackupRequest_Mode) Enum() *BackupRequest_Mode {
	p := new(BackupRequest_Mode)
	*p = x
	return p
}

func (x BackupRequest_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupRequest_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_medusa_medusa_proto_enumTypes[1].Descriptor()
}

func (BackupRequest_Mode) Type() protoreflect.EnumType {
	return &file_pkg_medusa_medusa_proto_enumTypes[1]
}

func (x BackupRequest_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackupRequest_Mode.Descriptor instead.
func (BackupRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{0, 0}
}

type BackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode BackupRequest_Mode `protobuf:"varint,2,opt,name=mode,proto3,enum=BackupRequest_Mode" json:"mode,omitempty"`
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{0}
}

func (x *BackupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupRequest) GetMode() BackupRequest_Mode {
	if x != nil {
		return x.Mode
	}
	return BackupRequest_DIFFERENTIAL
}

type BackupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackupName string     `protobuf:"bytes,1,opt,name=backupName,proto3" json:"backupName,omitempty"`
	Status     StatusType `protobuf:"varint,2,opt,name=status,proto3,enum=StatusType" json:"status,omitempty"`
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResponse.ProtoReflect.Descriptor instead.
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{1}
}

func (x *BackupResponse) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

func (x *BackupResponse) GetStatus() StatusType {
	if x != nil {
		return x.Status
	}
	return StatusType_IN_PROGRESS
}

type BackupStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackupName string `protobuf:"bytes,1,opt,name=backupName,proto3" json:"backupName,omitempty"`
}

func (x *BackupStatusRequest) Reset() {
	*x = BackupStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStatusRequest) ProtoMessage() {}

func (x *BackupStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStatusRequest.ProtoReflect.Descriptor instead.
func (*BackupStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{2}
}

func (x *BackupStatusRequest) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

type BackupStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FinishedNodes   []string   `protobuf:"bytes,1,rep,name=finishedNodes,proto3" json:"finishedNodes,omitempty"`
	UnfinishedNodes []string   `protobuf:"bytes,2,rep,name=unfinishedNodes,proto3" json:"unfinishedNodes,omitempty"`
	MissingNodes    []string   `protobuf:"bytes,3,rep,name=missingNodes,proto3" json:"missingNodes,omitempty"`
	StartTime       string     `protobuf:"bytes,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	FinishTime      string     `protobuf:"bytes,5,opt,name=finishTime,proto3" json:"finishTime,omitempty"`
	Status          StatusType `protobuf:"varint,6,opt,name=status,proto3,enum=StatusType" json:"status,omitempty"`
}

func (x *BackupStatusResponse) Reset() {
	*x = BackupStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStatusResponse) ProtoMessage() {}

func (x *BackupStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStatusResponse.ProtoReflect.Descriptor instead.
func (*BackupStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{3}
}

func (x *BackupStatusResponse) GetFinishedNodes() []string {
	if x != nil {
		return x.FinishedNodes
	}
	return nil
}

func (x *BackupStatusResponse) GetUnfinishedNodes() []string {
	if x != nil {
		return x.UnfinishedNodes
	}
	return nil
}

func (x *BackupStatusResponse) GetMissingNodes() []string {
	if x != nil {
		return x.MissingNodes
	}
	return nil
}

func (x *BackupStatusResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *BackupStatusResponse) GetFinishTime() string {
	if x != nil {
		return x.FinishTime
	}
	return ""
}

func (x *BackupStatusResponse) GetStatus() StatusType {
	if x != nil {
		return x.Status
	}
	return StatusType_IN_PROGRESS
}

type DeleteBackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteBackupRequest) Reset() {
	*x = DeleteBackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupRequest) ProtoMessage() {}

func (x *DeleteBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBackupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteBackupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status StatusType `protobuf:"varint,2,opt,name=status,proto3,enum=StatusType" json:"status,omitempty"`
}

func (x *DeleteBackupResponse) Reset() {
	*x = DeleteBackupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupResponse) ProtoMessage() {}

func (x *DeleteBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupResponse.ProtoReflect.Descriptor instead.
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBackupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteBackupResponse) GetStatus() StatusType {
	if x != nil {
		return x.Status
	}
	return StatusType_IN_PROGRESS
}

type GetBackupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBackupsRequest) Reset() {
	*x = GetBackupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupsRequest) ProtoMessage() {}

func (x *GetBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupsRequest.ProtoReflect.Descriptor instead.
func (*GetBackupsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{6}
}

type GetBackupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backups       []*BackupSummary `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	OverallStatus StatusType       `protobuf:"varint,2,opt,name=overallStatus,proto3,enum=StatusType" json:"overallStatus,omitempty"`
}

func (x *GetBackupsResponse) Reset() {
	*x = GetBackupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupsResponse) ProtoMessage() {}

func (x *GetBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupsResponse.ProtoReflect.Descriptor instead.
func (*GetBackupsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{7}
}

func (x *GetBackupsResponse) GetBackups() []*BackupSummary {
	if x != nil {
		return x.Backups
	}
	return nil
}

func (x *GetBackupsResponse) GetOverallStatus() StatusType {
	if x != nil {
		return x.OverallStatus
	}
	return StatusType_IN_PROGRESS
}

type BackupSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackupName    string        `protobuf:"bytes,1,opt,name=backupName,proto3" json:"backupName,omitempty"`
	StartTime     int64         `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	FinishTime    int64         `protobuf:"varint,3,opt,name=finishTime,proto3" json:"finishTime,omitempty"`
	TotalNodes    int32         `protobuf:"varint,4,opt,name=totalNodes,proto3" json:"totalNodes,omitempty"`
	FinishedNodes int32         `protobuf:"varint,5,opt,name=finishedNodes,proto3" json:"finishedNodes,omitempty"`
	Nodes         []*BackupNode `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Status        StatusType    `protobuf:"varint,7,opt,name=status,proto3,enum=StatusType" json:"status,omitempty"`
	BackupType    string        `protobuf:"bytes,8,opt,name=backupType,proto3" json:"backupType,omitempty"`
}

func (x *BackupSummary) Reset() {
	*x = BackupSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSummary) ProtoMessage() {}

func (x *BackupSummary) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSummary.ProtoReflect.Descriptor instead.
func (*BackupSummary) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{8}
}

func (x *BackupSummary) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

func (x *BackupSummary) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *BackupSummary) GetFinishTime() int64 {
	if x != nil {
		return x.FinishTime
	}
	return 0
}

func (x *BackupSummary) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *BackupSummary) GetFinishedNodes() int32 {
	if x != nil {
		return x.FinishedNodes
	}
	return 0
}

func (x *BackupSummary) GetNodes() []*BackupNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *BackupSummary) GetStatus() StatusType {
	if x != nil {
		return x.Status
	}
	return StatusType_IN_PROGRESS
}

func (x *BackupSummary) GetBackupType() string {
	if x != nil {
		return x.BackupType
	}
	return ""
}

type BackupNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host       string  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Tokens     []int64 `protobuf:"varint,2,rep,packed,name=tokens,proto3" json:"tokens,omitempty"`
	Datacenter string  `protobuf:"bytes,3,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Rack       string  `protobuf:"bytes,4,opt,name=rack,proto3" json:"rack,omitempty"`
}

func (x *BackupNode) Reset() {
	*x = BackupNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupNode) ProtoMessage() {}

func (x *BackupNode) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupNode.ProtoReflect.Descriptor instead.
func (*BackupNode) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{9}
}

func (x *BackupNode) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *BackupNode) GetTokens() []int64 {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *BackupNode) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *BackupNode) GetRack() string {
	if x != nil {
		return x.Rack
	}
	return ""
}

type PurgeBackupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PurgeBackupsRequest) Reset() {
	*x = PurgeBackupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurgeBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeBackupsRequest) ProtoMessage() {}

func (x *PurgeBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeBackupsRequest.ProtoReflect.Descriptor instead.
func (*PurgeBackupsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{10}
}

type PurgeBackupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NbBackupsPurged           int32 `protobuf:"varint,1,opt,name=nbBackupsPurged,proto3" json:"nbBackupsPurged,omitempty"`
	NbObjectsPurged           int32 `protobuf:"varint,2,opt,name=nbObjectsPurged,proto3" json:"nbObjectsPurged,omitempty"`
	TotalPurgedSize           int64 `protobuf:"varint,3,opt,name=totalPurgedSize,proto3" json:"totalPurgedSize,omitempty"`
	TotalObjectsWithinGcGrace int32 `protobuf:"varint,4,opt,name=totalObjectsWithinGcGrace,proto3" json:"totalObjectsWithinGcGrace,omitempty"`
}

func (x *PurgeBackupsResponse) Reset() {
	*x = PurgeBackupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurgeBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeBackupsResponse) ProtoMessage() {}

func (x *PurgeBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeBackupsResponse.ProtoReflect.Descriptor instead.
func (*PurgeBackupsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{11}
}

func (x *PurgeBackupsResponse) GetNbBackupsPurged() int32 {
	if x != nil {
		return x.NbBackupsPurged
	}
	return 0
}

func (x *PurgeBackupsResponse) GetNbObjectsPurged() int32 {
	if x != nil {
		return x.NbObjectsPurged
	}
	return 0
}

func (x *PurgeBackupsResponse) GetTotalPurgedSize() int64 {
	if x != nil {
		return x.TotalPurgedSize
	}
	return 0
}

func (x *PurgeBackupsResponse) GetTotalObjectsWithinGcGrace() int32 {
	if x != nil {
		return x.TotalObjectsWithinGcGrace
	}
	return 0
}

type PrepareRestoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackupName string `protobuf:"bytes,1,opt,name=backupName,proto3" json:"backupName,omitempty"`
	Datacenter string `protobuf:"bytes,2,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	RestoreKey string `protobuf:"bytes,3,opt,name=restoreKey,proto3" json:"restoreKey,omitempty"`
}

func (x *PrepareRestoreRequest) Reset() {
	*x = PrepareRestoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRestoreRequest) ProtoMessage() {}

func (x *PrepareRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRestoreRequest.ProtoReflect.Descriptor instead.
func (*PrepareRestoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{12}
}

func (x *PrepareRestoreRequest) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

func (x *PrepareRestoreRequest) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *PrepareRestoreRequest) GetRestoreKey() string {
	if x != nil {
		return x.RestoreKey
	}
	return ""
}

type PrepareRestoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PrepareRestoreResponse) Reset() {
	*x = PrepareRestoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_medusa_medusa_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareRestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRestoreResponse) ProtoMessage() {}

func (x *PrepareRestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_medusa_medusa_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRestoreResponse.ProtoReflect.Descriptor instead.
func (*PrepareRestoreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_medusa_medusa_proto_rawDescGZIP(), []int{13}
}

var File_pkg_medusa_medusa_proto protoreflect.FileDescriptor

var file_pkg_medusa_medusa_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x64, 0x75, 0x73, 0x61, 0x2f, 0x6d, 0x65, 0x64,
	0x75, 0x73, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x0d, 0x42, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x27,
	0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x22, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x0c, 0x44, 0x49, 0x46, 0x46, 0x45, 0x52, 0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x55, 0x4c, 0x4c, 0x10, 0x01, 0x22, 0x55, 0x0a, 0x0e, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x35, 0x0a, 0x13, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xed, 0x01, 0x0a, 0x14, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x75, 0x6e, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0f, 0x75, 0x6e, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e,
	0x67, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x29, 0x0a, 0x13, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4f, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x23, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0b, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x71, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x52, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x12, 0x31, 0x0a, 0x0d, 0x6f, 0x76,
	0x65, 0x72, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d,
	0x6f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x9b, 0x02,
	0x0a, 0x0d, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12,
	0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x24, 0x0a,
	0x0d, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x62,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x22, 0x6c, 0x0a, 0x0a, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x63,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x61, 0x63, 0x6b, 0x22, 0x15, 0x0a, 0x13, 0x50, 0x75, 0x72,
	0x67, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0xd2, 0x01, 0x0a, 0x14, 0x50, 0x75, 0x72, 0x67, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x6e, 0x62, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x50, 0x75, 0x72, 0x67, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0f, 0x6e, 0x62, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x50, 0x75, 0x72,
	0x67, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x6e, 0x62, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x50, 0x75, 0x72, 0x67, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x6e, 0x62,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x50, 0x75, 0x72, 0x67, 0x65, 0x64, 0x12, 0x28, 0x0a,
	0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x75, 0x72, 0x67, 0x65, 0x64, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x75, 0x72,
	0x67, 0x65, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x3c, 0x0a, 0x19, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x57, 0x69, 0x74, 0x68, 0x69, 0x6e, 0x47, 0x63, 0x47,
	0x72, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x19, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x57, 0x69, 0x74, 0x68, 0x69, 0x6e, 0x47, 0x63,
	0x47, 0x72, 0x61, 0x63, 0x65, 0x22, 0x77, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1e,
	0x0a, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x18,
	0x0a, 0x16, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x43, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f,
	0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x32, 0x94, 0x03,
	0x0a, 0x06, 0x4d, 0x65, 0x64, 0x75, 0x73, 0x61, 0x12, 0x29, 0x0a, 0x06, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x12, 0x0e, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x12, 0x0e, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x14, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x12, 0x14, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x12, 0x12, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x50, 0x75, 0x72, 0x67, 0x65, 0x42, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x73, 0x12, 0x14, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x50, 0x75, 0x72,
	0x67, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x41, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x12, 0x16, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x50, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x6d, 0x65, 0x64, 0x75, 0x73, 0x61,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_medusa_medusa_proto_rawDescOnce sync.Once
	file_pkg_medusa_medusa_proto_rawDescData = file_pkg_medusa_medusa_proto_rawDesc
)

func file_pkg_medusa_medusa_proto_rawDescGZIP() []byte {
	file_pkg_medusa_medusa_proto_rawDescOnce.Do(func() {
		file_pkg_medusa_medusa_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_medusa_medusa_proto_rawDescData)
	})
	return file_pkg_medusa_medusa_proto_rawDescData
}

var file_pkg_medusa_medusa_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_medusa_medusa_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_medusa_medusa_proto_goTypes = []interface{}{
	(StatusType)(0),                // 0: StatusType
	(BackupRequest_Mode)(0),        // 1: BackupRequest.Mode
	(*BackupRequest)(nil),          // 2: BackupRequest
	(*BackupResponse)(nil),         // 3: BackupResponse
	(*BackupStatusRequest)(nil),    // 4: BackupStatusRequest
	(*BackupStatusResponse)(nil),   // 5: BackupStatusResponse
	(*DeleteBackupRequest)(nil),    // 6: DeleteBackupRequest
	(*DeleteBackupResponse)(nil),   // 7: DeleteBackupResponse
	(*GetBackupsRequest)(nil),      // 8: GetBackupsRequest
	(*GetBackupsResponse)(nil),     // 9: GetBackupsResponse
	(*BackupSummary)(nil),          // 10: BackupSummary
	(*BackupNode)(nil),             // 11: BackupNode
	(*PurgeBackupsRequest)(nil),    // 12: PurgeBackupsRequest
	(*PurgeBackupsResponse)(nil),   // 13: PurgeBackupsResponse
	(*PrepareRestoreRequest)(nil),  // 14: PrepareRestoreRequest
	(*PrepareRestoreResponse)(nil), // 15: PrepareRestoreResponse
}
var file_pkg_medusa_medusa_proto_depIdxs = []int32{
	1,  // 0: BackupRequest.mode:type_name -> BackupRequest.Mode
	0,  // 1: BackupResponse.status:type_name -> StatusType
	0,  // 2: BackupStatusResponse.status:type_name -> StatusType
	0,  // 3: DeleteBackupResponse.status:type_name -> StatusType
	10, // 4: GetBackupsResponse.backups:type_name -> BackupSummary
	0,  // 5: GetBackupsResponse.overallStatus:type_name -> StatusType
	11, // 6: BackupSummary.nodes:type_name -> BackupNode
	0,  // 7: BackupSummary.status:type_name -> StatusType
	2,  // 8: Medusa.Backup:input_type -> BackupRequest
	2,  // 9: Medusa.AsyncBackup:input_type -> BackupRequest
	4,  // 10: Medusa.BackupStatus:input_type -> BackupStatusRequest
	6,  // 11: Medusa.DeleteBackup:input_type -> DeleteBackupRequest
	8,  // 12: Medusa.GetBackups:input_type -> GetBackupsRequest
	12, // 13: Medusa.PurgeBackups:input_type -> PurgeBackupsRequest
	14, // 14: Medusa.PrepareRestore:input_type -> PrepareRestoreRequest
	3,  // 15: Medusa.Backup:output_type -> BackupResponse
	3,  // 16: Medusa.AsyncBackup:output_type -> BackupResponse
	5,  // 17: Medusa.BackupStatus:output_type -> BackupStatusResponse
	7,  // 18: Medusa.DeleteBackup:output_type -> DeleteBackupResponse
	9,  // 19: Medusa.GetBackups:output_type -> GetBackupsResponse
	13, // 20: Medusa.PurgeBackups:output_type -> PurgeBackupsResponse
	15, // 21: Medusa.PrepareRestore:output_type -> PrepareRestoreResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_medusa_medusa_proto_init() }
func file_pkg_medusa_medusa_proto_init() {
	if File_pkg_medusa_medusa_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_medusa_medusa_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBackupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBackupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBackupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurgeBackupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurgeBackupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareRestoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_medusa_medusa_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareRestoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_medusa_medusa_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_medusa_medusa_proto_goTypes,
		DependencyIndexes: file_pkg_medusa_medusa_proto_depIdxs,
		EnumInfos:         file_pkg_medusa_medusa_proto_enumTypes,
		MessageInfos:      file_pkg_medusa_medusa_proto_msgTypes,
	}.Build()
	File_pkg_medusa_medusa_proto = out.File
	file_pkg_medusa_medusa_proto_rawDesc = nil
	file_pkg_medusa_medusa_proto_goTypes = nil
	file_pkg_medusa_medusa_proto_depIdxs = nil
}
