help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

.PHONY: test
test: ## run unit tests
	@echo "\n🛠️  Running unit tests..."
	go test ./...

.PHONY: build
build: ## build binaries
	@echo "\n🔧  Building Go binaries..."
	GOOS=darwin GOARCH=amd64 go build -o bin/admission-webhook-darwin-amd64 .
	GOOS=linux GOARCH=amd64 go build -o bin/admission-webhook-linux-amd64 .

.PHONY: docker-build
docker-build: ## build webhook docker image
	@echo "\n📦 Building simple-kubernetes-webhook Docker image..."
	cd ../.. && docker build -t k8ssandra-secrets-webhook -f cmd/secrets-webhook/Dockerfile .
