apiVersion: v1
items:
- apiVersion: medusa.k8ssandra.io/v1alpha1
  kind: MedusaRestoreJob
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"medusa.k8ssandra.io/v1alpha1","kind":"MedusaRestoreJob","metadata":{"annotations":{},"name":"cassandra-vm-backup-mig","namespace":"migration"},"spec":{"backup":"final-ocp","cassandraDatacenter":"dc1"}}
    creationTimestamp: "2025-04-24T12:49:33Z"
    generation: 1
    name: cassandra-vm-backup-mig
    namespace: migration
    ownerReferences:
    - apiVersion: cassandra.datastax.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: CassandraDatacenter
      name: dc1
      uid: 27a13a93-0afd-41bb-aaca-2d34912cc429
    resourceVersion: "1106002836"
    uid: 62f26f5a-87e5-4ed7-b63e-13a48236f8f8
  spec:
    backup: final-ocp
    cassandraDatacenter: dc1
- apiVersion: medusa.k8ssandra.io/v1alpha1
  kind: MedusaRestoreJob
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"medusa.k8ssandra.io/v1alpha1","kind":"MedusaRestoreJob","metadata":{"annotations":{},"name":"migration","namespace":"migration"},"spec":{"backup":"final-ocp","cassandraDatacenter":"DC1"}}
    creationTimestamp: "2025-04-24T12:58:20Z"
    generation: 1
    name: migration
    namespace: migration
    resourceVersion: "1106041856"
    uid: 93c74085-0eb9-41f1-9040-8277af6480eb
  spec:
    backup: final-ocp
    cassandraDatacenter: DC1
kind: List
metadata:
  resourceVersion: ""


apiVersion: medusa.k8ssandra.io/v1alpha1
kind: MedusaRestoreJob
metadata:
  name: cassandra-vm-backup-mig
  namespace: radovan-dse-ssbr-7tk7x4n7  
spec:
  backup: medusa-backup1
  cassandraDatacenter: dc1
