apiVersion: medusa.k8ssandra.io/v1alpha1
kind: MedusaTask
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"medusa.k8ssandra.io/v1alpha1","kind":"MedusaTask","metadata":{"annotations":{},"name":"sync-backups-1","namespace":"migration"},"spec":{"cassandraDatacenter":"dc1","operation":"sync"}}
  creationTimestamp: "2025-04-24T12:38:55Z"
  generation: 1
  name: sync-backups-1
  namespace: migration
  ownerReferences:
  - apiVersion: cassandra.datastax.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CassandraDatacenter
    name: dc1
    uid: 27a13a93-0afd-41bb-aaca-2d34912cc429
  resourceVersion: "1105955307"
  uid: c612759e-393b-4b98-9348-f7a433eeb1e9
spec:
  cassandraDatacenter: dc1
  operation: sync
status:
  finishTime: "2025-04-24T12:39:10Z"
  finished:
  - podName: k8ssandra-cluster-dc1-rac1-sts-2
  startTime: "2025-04-24T12:39:10Z"



apiVersion: medusa.k8ssandra.io/v1alpha1
kind: MedusaTask
metadata:
  name: sync-backups-1
  namespace: radovan-dse-ssbr-7tk7x4n7
spec:
  cassandraDatacenter: dc1
  operation: sync
