resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

namePrefix: k8ssandra-operator-

patchesJson6902:
- target:
    group: admissionregistration.k8s.io
    version: v1
    name: k8ssandra-operator-validating-webhook-configuration
    kind: ValidatingWebhookConfiguration
  patch: |-
    - op: replace
      path: /webhooks/1/clientConfig/service/name
      value: k8ssandra-operator-webhook-service
    - op: replace
      path: /webhooks/0/clientConfig/service/name
      value: k8ssandra-operator-webhook-service
- target:
    group: admissionregistration.k8s.io
    version: v1
    name: k8ssandra-operator-mutating-webhook-configuration
    kind: MutatingWebhookConfiguration
  patch: |-
    - op: replace
      path: /webhooks/0/clientConfig/service/name
      value: k8ssandra-operator-webhook-service
    - op: add
      path: /webhooks/0/objectSelector
      value:
        matchLabels:
          app.kubernetes.io/created-by: cass-operator