apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}-leader-election-role
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
rules:
