# This is a temporary component that will be removed when https://github.com/k8ssandra/k8ssandra-operator/issues/212
# is done.
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesJson6902:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MANAGEMENT_API_HEAP_SIZE
          value: 16M
    target:
      group: apps
      kind: Deployment
      name: k8ssandra-operator
      version: v1