# permissions for end users to view k8ssandratasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8ssandratask-viewer-role
rules:
- apiGroups:
  - control.k8ssandra.io
  resources:
  - k8ssandratasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - control.k8ssandra.io
  resources:
  - k8ssandratasks/status
  verbs:
  - get
