# permissions for end users to edit k8ssandraclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8ssandracluster-editor-role
rules:
- apiGroups:
  - k8ssandra.io
  resources:
  - k8ssandraclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8ssandra.io
  resources:
  - k8ssandraclusters/status
  verbs:
  - get
