//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package encryption

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientEncryptionOptions) DeepCopyInto(out *ClientEncryptionOptions) {
	*out = *in
	in.EncryptionSettings.DeepCopyInto(&out.EncryptionSettings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientEncryptionOptions.
func (in *ClientEncryptionOptions) DeepCopy() *ClientEncryptionOptions {
	if in == nil {
		return nil
	}
	out := new(ClientEncryptionOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionSettings) DeepCopyInto(out *EncryptionSettings) {
	*out = *in
	if in.AcceptedProtocols != nil {
		in, out := &in.AcceptedProtocols, &out.AcceptedProtocols
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CipherSuites != nil {
		in, out := &in.CipherSuites, &out.CipherSuites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionSettings.
func (in *EncryptionSettings) DeepCopy() *EncryptionSettings {
	if in == nil {
		return nil
	}
	out := new(EncryptionSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerEncryptionOptions) DeepCopyInto(out *ServerEncryptionOptions) {
	*out = *in
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
	in.EncryptionSettings.DeepCopyInto(&out.EncryptionSettings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerEncryptionOptions.
func (in *ServerEncryptionOptions) DeepCopy() *ServerEncryptionOptions {
	if in == nil {
		return nil
	}
	out := new(ServerEncryptionOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Stores) DeepCopyInto(out *Stores) {
	*out = *in
	out.KeystoreSecretRef = in.KeystoreSecretRef
	out.TruststoreSecretRef = in.TruststoreSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Stores.
func (in *Stores) DeepCopy() *Stores {
	if in == nil {
		return nil
	}
	out := new(Stores)
	in.DeepCopyInto(out)
	return out
}
