apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesJson6902:
- target:
    group: apps
    version: v1
    name: k8ssandra-operator
    kind: Deployment
  patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/env/0/valueFrom
    - op: add
      path: /spec/template/spec/containers/0/env/0/value
      value: ""
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: Role
    name: k8ssandra-operator
  patch: |-
    - op: replace
      path: /kind
      value: ClusterRole
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: k8ssandra-operator
  patch: |-
    - op: replace
      path: /roleRef/kind
      value: ClusterRole
    - op: replace
      path: /kind
      value: ClusterRoleBinding
    - op: replace
      path: /subjects/0/name
      value: k8ssandra-operator
