apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8ssandra-operator

resources:
  - ../../default
  - ../../../../../cass-operator/config/deployments/default

components:
  - ../../../components/data-plane