{
 "title": "Cassandra Cluster Condensed",
 "description": "Single pane of glass for most important Cassandra metrics",
 "tags": [ "os" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "Prometheus" },
   { "name": "by", "label": "Group By", "query": "cluster,dc,rack,instance" },
   {
    "name": "rate",
    "label": "Rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_thread_pools_completed_tasks{}, cluster)"
    }
   },
   {
    "name": "dc",
    "label": "DataCenter",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\"}, datacenter)"
    }
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\"}, rack)"
    }
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_table_read_total_latency{cluster=~\"$cluster\", datacenter=~\"$dc\"}, keyspace)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_table_read_total_latency{cluster=~\"$cluster\", datacenter=~\"$dc\", keyspace=~\"$keyspace\"}, table)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\"}, pod_name)"
    }
   },
   {
    "name": "latency",
    "label": "Percentile",
    "query": "0.999,0.99,0.98,0.95,0.90,0.75,0.50"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes Up",
   "type": "stat",
   "description": "Nodes that are currently running in this time window",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by(pod_name) (org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"} >= 0)) or vector(0)"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "stat",
   "description": "Nodes that are currently not running in this time window",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(absent(sum(rate(org_apache_cassandra_metrics_compaction_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[1m:30s])))) OR vector(0)"
    }
   ]
  },
  {
   "title": "CQL Clients",
   "type": "stat",
   "description": "Number of connected clients during this time window",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_client_connected_native_clients{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "CQL Requests / $rate",
   "type": "stat",
   "description": "Rate of CQL requests during this window",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Dropped Messages / $rate",
   "type": "stat",
   "description": "Rate of Dropped requests during this window",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_table_dropped_mutations{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Tombstone reads / $rate",
   "type": "stat",
   "description": "Tombstone reads over the last $rate",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_table_tombstone_scanned_histogram_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Timeouts / $rate",
   "type": "stat",
   "description": "Client timeouts over the last $rate",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_client_request_timeouts_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Hints / $rate",
   "type": "stat",
   "description": "Hints stored over the last $rate",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_storage_total_hints{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Compactions / $rate",
   "type": "stat",
   "description": "Rate of compactions during this window",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(org_apache_cassandra_metrics_compaction_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Pending Compactions / $rate",
   "type": "stat",
   "description": "Rate of compactions during this window",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Data Size",
   "type": "stat",
   "description": "Data",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_table_live_disk_space_used{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "GC Time / $rate",
   "type": "stat",
   "description": "Data",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_g1_old_generation_time{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate])) + sum(rate(jvm_gc_g1_young_generation_time{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Condensed Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Served / $by / $rate",
   "type": "timeseries",
   "description": "(no keyspace/table filters apply)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate])) by ($by, request_type)",
     "legendFormat": "$by:{{$by}} {{request_type}}"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_client_connected_native_clients{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}) by ($by)",
     "legendFormat": "$by:{{$by}}:Clients Connected"
    }
   ]
  },
  {
   "title": "Coordinator $latency Latency / $by",
   "type": "timeseries",
   "description": "(no keyspace/table filters apply)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($latency, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate])) by (le, request_type, $by))",
     "legendFormat": "$by:{{$by}} {{$latency}} {{request_type}}"
    }
   ]
  },
  {
   "title": "Memtable Space $keyspace.$table / $by",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_table_memtable_off_heap_size{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}} : Off Heap"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_table_memtable_on_heap_size{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}} : On Heap"
    },
    {
     "expr": "sum(idelta(org_apache_cassandra_metrics_table_memtable_switch_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}} : Flushes"
    },
    {
     "expr": "sum(idelta(org_apache_cassandra_metrics_table_pending_flushes{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}} : Pending Flushes"
    }
   ]
  },
  {
   "title": "Compactions $keyspace.$table / $by",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_table_compaction_bytes_written{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{by}} : Bytes Compacted"
    },
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{by}} : Pending Compactions"
    },
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_compaction_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{by}} : Completed Compactions"
    }
   ]
  },
  {
   "title": "Table $latency Latency / $by",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_range_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Local Range Scan"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_read_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Local Read"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_write_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Local Write"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_coordinator_read_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Coordinator Read"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_coordinator_scan_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Coordinator Range Scan"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_coordinator_write_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Coordinator Write"
    }
   ]
  },
  {
   "title": "Streaming / $by / $rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_streaming_total_incoming_bytes{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}}: Incoming Stream"
    },
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_streaming_total_outgoing_bytes{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}}: Outgoing Stream"
    }
   ]
  }
 ]
}
{
 "title": "Cassandra Overview",
 "tags": [
  "Cassandra",
  "Overview"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "Prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_thread_pools_completed_tasks{}, cluster)"
    }
   },
   {
    "name": "dc",
    "label": "Datacenter",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\"}, datacenter)"
    }
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\"}, rack)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_compaction_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\"}, pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Throughputs (Coordinator Perspective)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Throughputs",
   "type": "timeseries",
   "description": "Total Requests Per Cluster, by Request Type",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "Cassandra {{request_type}}"
    }
   ]
  },
  {
   "title": "Error throughputs",
   "type": "timeseries",
   "description": "Total Timeouts, Failures, Unavailable Rates for each cluster",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_failures_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{request_type}} failures"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_timeouts_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{request_type}} timeouts"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_unavailables_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{request_type}} unavailable errors"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_unfinished_commit{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{request_type}} unfinished commit errors"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_condition_not_met{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{request_type}} condition not met errors"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_contention_histogram_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{request_type}} contention histogram errors"
    }
   ]
  },
  {
   "title": "Read / Write Distribution",
   "type": "gauge",
   "description": "Part of reads in the total of standard requests (Reads+Writes). CAS, Views, ... operations are ignored.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum by (cluster) (rate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Read\"}[1m:30s]))  ) / (sum by (cluster) (rate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Read\"}[1m:30s])) + sum by (cluster) (rate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Write\"}[1m:30s])))"
    }
   ]
  },
  {
   "title": "Read Latency (98 - 999th percentile)",
   "type": "timeseries",
   "description": "Read latency for coordinated reads",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.98, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Read\"}[1m:30s])) by (le, cluster))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Read\"}[1m:30s])) by (le, cluster))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Read\"}[1m:30s])) by (le, cluster))",
     "legendFormat": "p999"
    }
   ]
  },
  {
   "title": "Write Latency (98th - p999 Percentile)",
   "type": "timeseries",
   "description": "Write latency for coordinated writes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.98, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Write\"}[1m:30s])) by (le, cluster))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Write\"}[1m:30s])) by (le, cluster))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Write\"}[1m:30s])) by (le, cluster))",
     "legendFormat": "p999"
    }
   ]
  },
  {
   "title": "Other Latencies",
   "type": "timeseries",
   "description": "Other p99 latencies for coordinated requests",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type!~\"Write|Read|.*-.*\"}[1m:30s])) by (le, request_type, cluster))",
     "legendFormat": "p99 {{request_type}}"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes Status",
   "type": "grafana-polystat-panel",
   "description": "Nodes Status uses Internal/Gossip activity. Be mindful that if Native or Thrift protocol are disabled, the nodes won't be reachable, and still marked up",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (cluster, dc, rack, pod_name) (changes(org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", pool_name=\"GossipStage\", pool_type=\"internal\"}[1m:30s])) > bool 0",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Nodes Count",
   "type": "stat",
   "description": "Nodes up and down in the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (cluster) (max by (cluster, dc, rack, instance) (org_apache_cassandra_metrics_compaction_completed_tasks{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}))",
     "legendFormat": "Total Number Of Nodes"
    }
   ]
  },
  {
   "title": "Nodes Status History",
   "type": "timeseries",
   "description": "Nodes up and down in the cluster per protocol/activity",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (cluster) (max by (cluster, dc, rack, instance) (org_apache_cassandra_metrics_compaction_completed_tasks{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}))",
     "legendFormat": "Total Number Of Nodes"
    }
   ]
  },
  {
   "title": "Data Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "description": "Disk space used ordered (fullest disks first)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(host, device) (host_filesystem_used_ratio{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "{{host}} - {{device}}"
    }
   ]
  },
  {
   "title": "Cassandra cluster Data Size",
   "type": "timeseries",
   "description": "Total sizes of the data on distinct nodes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster) (org_apache_cassandra_metrics_table_live_disk_space_used{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "Live space - {{cluster}}"
    },
    {
     "expr": "sum by (cluster) (org_apache_cassandra_metrics_table_total_disk_space_used{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "Total space - {{cluster}}"
    }
   ]
  },
  {
   "title": "SSTable Count",
   "type": "timeseries",
   "description": "SSTable Count Max and Average per table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (cluster, keyspace, table) (org_apache_cassandra_metrics_table_live_ss_table_count{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "Table - {{keyspace}}.{{table}}"
    },
    {
     "expr": "max by (cluster) (org_apache_cassandra_metrics_table_live_ss_table_count{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "Max in cluster - {{cluster}}"
    }
   ]
  },
  {
   "title": "Pending Compactions",
   "type": "timeseries",
   "description": "Maximum pending compactions on any node in the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (cluster) (org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Pending Compactions per Table",
   "type": "timeseries",
   "description": "Maximum pending compactions per table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (cluster, keyspace, table) (org_apache_cassandra_metrics_table_pending_compactions{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "max for {{keyspace}}.{{table}}"
    }
   ]
  },
  {
   "title": "Cassandra Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "timeseries",
   "description": "Cluster wide pending threads, by thread pool name",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, pool_name) (org_apache_cassandra_metrics_thread_pools_pending_tasks{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "{{cluster}} - pending {{pool_name}}"
    }
   ]
  },
  {
   "title": "Blocked Tasks",
   "type": "timeseries",
   "description": "Cluster wide blocked threads, by thread pool name",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, pool_name) (rate(org_apache_cassandra_metrics_thread_pools_total_blocked_tasks{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{cluster}} - blocked {{pool_name}}"
    }
   ]
  },
  {
   "title": "Dropped Messages",
   "type": "timeseries",
   "description": "Dropped messages rate summed by message type and cluster",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, message_type) (rate(org_apache_cassandra_metrics_dropped_message_dropped_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{cluster}} - dropped {{message_type}}"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "timeseries",
   "description": "active threads summed per cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, pool_name) (org_apache_cassandra_metrics_thread_pools_active_tasks{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "{{cluster}} - active {{pool_name}}"
    }
   ]
  },
  {
   "title": "Hinted Handoff",
   "type": "timeseries",
   "description": "Sum of hints being handed off per cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster) (org_apache_cassandra_metrics_storage_total_hints_in_progress{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Hardware / Operating System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Maximum CPU utilisation (max 100%)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (cluster) (1 - (sum by (host) (rate(host_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s])) / sum by (host) (rate(host_cpu_seconds_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))))",
     "legendFormat": "max {{host}}"
    },
    {
     "expr": "min by (cluster) (1 - (sum by (host) (rate(host_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s])) / sum by (host) (rate(host_cpu_seconds_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))))",
     "legendFormat": "min {{host}}"
    },
    {
     "expr": "avg by (cluster) (1 - (sum by (host) (rate(host_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s])) / sum by (host) (rate(host_cpu_seconds_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))))",
     "legendFormat": "avg {{host}}"
    }
   ]
  },
  {
   "title": "Unix Load (1m rate)",
   "type": "timeseries",
   "description": "Max Unix load on a node for a cluster",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (cluster) (host_load1{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (host_load1{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (host_load1{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "description": "Maximum Memory allocated per usage (worst node) - excludes caches, buffers, etc",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (cluster) (host_memory_used_bytes{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "max {{host}}"
    },
    {
     "expr": "min by (cluster) (host_memory_used_bytes{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "min {{host}}"
    },
    {
     "expr": "avg by (cluster) (host_memory_used_bytes{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "avg {{host}}"
    }
   ]
  },
  {
   "title": "Disk Read Thoughput",
   "type": "timeseries",
   "description": "Disk read throughput",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max by (cluster) (rate(host_disk_read_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))",
     "legendFormat": "max {{host}}"
    },
    {
     "expr": "min by (cluster) (rate(host_disk_read_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))",
     "legendFormat": "min {{host}}"
    },
    {
     "expr": "avg by (cluster) (rate(host_disk_read_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))",
     "legendFormat": "avg {{host}}"
    }
   ]
  },
  {
   "title": "Disk Write Thoughput",
   "type": "timeseries",
   "description": "Disk write throughput",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max by (cluster) (rate(host_disk_written_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))",
     "legendFormat": "max {{host}}"
    },
    {
     "expr": "min by (cluster) (rate(host_disk_written_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))",
     "legendFormat": "min {{host}}"
    },
    {
     "expr": "avg by (cluster) (rate(host_disk_written_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "avg {{host}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Network In and Out per cluster",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(host_network_transmit_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "outgoing"
    },
    {
     "expr": "sum by (cluster) (rate(host_network_receive_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "incoming"
    }
   ]
  },
  {
   "title": "JVM / Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Application Throughput (% time NOT doing GC)",
   "type": "timeseries",
   "description": "Percentage of the time the node is *not* doing a GC, thus Cassandra is not stopped for GC",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (cluster) (1 - (sum by (cluster, dc, rack, instance) (rate(jvm_gc_g1_young_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]) + rate(jvm_gc_g1_old_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s])) / 1000))",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (1 - (sum by (cluster, dc, rack, instance) (rate(jvm_gc_g1_young_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]) + rate(jvm_gc_g1_old_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s])) / 1000))",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (1 - (sum by (cluster, dc, rack, instance) (rate(jvm_gc_g1_young_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]) + rate(jvm_gc_g1_old_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s])) / 1000))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "timeseries",
   "description": "Garbage collection duration",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (cluster) (rate(jvm_gc_g1_young_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (rate(jvm_gc_g1_young_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (rate(jvm_gc_g1_young_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "JVM Memory Utilisation",
   "type": "timeseries",
   "description": "Maximum JVM Heap Memory size (worst node) and minimum available heap size",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(jvm_memory_bytes_used) by(area)",
     "legendFormat": "max {{area}}"
    },
    {
     "expr": "min by (cluster)\n        (jvm_memory_bytes_used{memory_type=\"heap\", cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster)\n        (mcac_jvm_memory_used{memory_type=\"heap\", cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "min by ( cluster)\n        (mcac_jvm_memory_max{memory_type=\"heap\", cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "Heap memory available"
    }
   ]
  }
 ]
}