{{- if not .Values.disableCrdUpgraderJob }}
{{- if .Values.global.clusterScopedResources }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}-crd-upgrader-k8ssandra
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
    {{- with include "k8ssandra-common.annotations" . }}
    {{- . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}