# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager v1.0. Check https://cert-manager.io/docs/installation/upgrading/ for breaking changes.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: k8ssandra-operator-selfsigned-issuer
  namespace: system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8ssandra-operator-serving-cert  # this name should match the one appeared in kustomizeconfig.yaml
  namespace: system
spec:
  # $(SERVICE_NAME) and $(SERVICE_NAMESPACE) will be substituted by kustomize
  dnsNames:
  - $(SERVICE_NAME_K8S).$(SERVICE_NAMESPACE_K8S).svc
  - $(SERVICE_NAME_K8S).$(SERVICE_NAMESPACE_K8S).svc.cluster.local
  issuerRef:
    kind: Issuer
    name: k8ssandra-operator-selfsigned-issuer
  secretName: k8ssandra-operator-webhook-server-cert # this secret will not be prefixed, since it's not managed by kustomize

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8ssandra-secrets-serving-cert
  namespace: system
spec:
  # $(SECRETS_SERVICE_NAME) and $(SECRETS_SERVICE_NAMESPACE) will be substituted by kustomize
  dnsNames:
  - $(SECRETS_SERVICE_NAME_K8S).$(SECRETS_SERVICE_NAMESPACE_K8S).svc
  - $(SECRETS_SERVICE_NAME_K8S).$(SECRETS_SERVICE_NAMESPACE_K8S).svc.cluster.local
  issuerRef:
    kind: Issuer
    name: k8ssandra-operator-selfsigned-issuer
  secretName: k8ssandra-secrets-webhook-server-cert