apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cass-operator-manager-res-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cass-operator-manager-crrole  # Use the full name to explicitly reference the cass-operator ClusterRole
subjects:
- kind: ServiceAccount
  name: cass-operator-manager
  namespace: k8ssandra-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cass-operator
  name: cass-operator-manager-rolebinding
  namespace: k8ssandra-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cass-operator-manager-crrole
subjects:
- kind: ServiceAccount
  name: cass-operator-controller-manager
  namespace: k8ssandra-operator
