# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/k8ssandra.io_k8ssandraclusters.yaml
- bases/stargate.k8ssandra.io_stargates.yaml
- bases/config.k8ssandra.io_clientconfigs.yaml
- bases/replication.k8ssandra.io_replicatedsecrets.yaml
- bases/reaper.k8ssandra.io_reapers.yaml
- bases/medusa.k8ssandra.io_cassandrabackups.yaml
- bases/medusa.k8ssandra.io_cassandrarestores.yaml
- bases/medusa.k8ssandra.io_medusatasks.yaml
- bases/medusa.k8ssandra.io_medusabackups.yaml
- bases/medusa.k8ssandra.io_medusabackupjobs.yaml
- bases/medusa.k8ssandra.io_medusarestorejobs.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
- path: patches/remove_config_validation.json
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: k8ssandraclusters.k8ssandra.io

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# - patches/webhook_in_k8ssandraclusters.yaml
#- patches/webhook_in_stargates.yaml
#- patches/webhook_in_replicatedsecrets.yaml
#- patches/webhook_in_reapers.yaml
#- patches/webhook_in_cassandrabackups.yaml
#- patches/webhook_in_cassandrarestores.yaml
#- patches/webhook_in_MedusaTasks.yaml
#- patches/webhook_in_medusabackups.yaml
#- patches/webhook_in_medusabackupjobs.yaml
#- patches/webhook_in_medusarestorejobs.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_k8ssandraclusters.yaml
#- patches/cainjection_in_stargates.yaml
#- patches/cainjection_in_replicatedsecrets.yaml
#- patches/cainjection_in_reapers.yaml
#- patches/cainjection_in_cassandrabackups.yaml
#- patches/cainjection_in_cassandrarestores.yaml
#- patches/cainjection_in_MedusaTasks.yaml
#- patches/cainjection_in_medusabackups.yaml
#- patches/cainjection_in_medusabackupjobs.yaml
#- patches/cainjection_in_medusarestorejobs.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
