{{- if .Values.global.clusterScoped }}
{{- if .Values.global.clusterScopedResources }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  {{- with include "k8ssandra-common.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
    - discovery.k8s.io
  resources:
    - endpointslices
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
{{- end }}
{{- end }}
