{{- if not .Values.global.clusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  {{- with include "k8ssandra-common.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
    - secrets
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
    - statefulsets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - batch
  resources:
    - cronjobs
  verbs:
    - create
    - delete
    - get
    - list
    - update
    - watch
- apiGroups:
    - cassandra.datastax.com
  resources:
    - cassandradatacenters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - config.k8ssandra.io
  resources:
    - clientconfigs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - control.k8ssandra.io
  resources:
    - cassandratasks
    - k8ssandratasks
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - control.k8ssandra.io
  resources:
    - cassandratasks/status
  verbs:
    - get
- apiGroups:
    - control.k8ssandra.io
  resources:
    - k8ssandratasks/finalizers
  verbs:
    - update
- apiGroups:
    - control.k8ssandra.io
  resources:
    - k8ssandratasks/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - discovery.k8s.io
  resources:
    - endpointslices
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - k8ssandra.io
  resources:
    - clientconfigs
    - k8ssandraclusters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - k8ssandra.io
  resources:
    - k8ssandraclusters/finalizers
  verbs:
    - update
- apiGroups:
    - k8ssandra.io
  resources:
    - k8ssandraclusters/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - medusa.k8ssandra.io
  resources:
    - cassandradatacenters
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - medusa.k8ssandra.io
  resources:
    - medusabackupjobs
    - medusabackups
    - medusabackupschedules
    - medusaconfigurations
    - medusatasks
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - medusa.k8ssandra.io
  resources:
    - medusabackupjobs/finalizers
    - medusabackups/finalizers
    - medusabackupschedules/finalizers
    - medusaconfigurations/finalizers
    - medusatasks/finalizers
  verbs:
    - update
- apiGroups:
    - medusa.k8ssandra.io
  resources:
    - medusabackupjobs/status
    - medusabackups/status
    - medusabackupschedules/status
    - medusaconfigurations/status
    - medusarestorejobs/status
    - medusatasks/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - medusa.k8ssandra.io
  resources:
    - medusarestorejobs
  verbs:
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - monitoring.coreos.com
  resources:
    - servicemonitors
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - reaper.k8ssandra.io
  resources:
    - reapers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - reaper.k8ssandra.io
  resources:
    - reapers/finalizers
  verbs:
    - update
- apiGroups:
    - reaper.k8ssandra.io
  resources:
    - reapers/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - replication.k8ssandra.io
  resources:
    - replicatedsecrets
  verbs:
    - create
    - delete
    - get
    - list
    - update
    - watch
- apiGroups:
    - replication.k8ssandra.io
  resources:
    - replicatedsecrets/finalizers
  verbs:
    - update
- apiGroups:
    - replication.k8ssandra.io
  resources:
    - replicatedsecrets/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - stargate.k8ssandra.io
  resources:
    - stargates
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - stargate.k8ssandra.io
  resources:
    - stargates/finalizers
  verbs:
    - update
- apiGroups:
    - stargate.k8ssandra.io
  resources:
    - stargates/status
  verbs:
    - get
    - patch
    - update
{{- end }}
