{{- if semverCompare ">=1.24-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8ssandra-common.serviceAccountName" . }}-token
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "k8ssandra-common.serviceAccountName" . }}
    {{- with include "k8ssandra-common.annotations" . }}
      {{- . | nindent 4 }}
    {{- end }}
type: kubernetes.io/service-account-token
{{- end }}