apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}-webhook-service
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  {{- with include "k8ssandra-common.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: k8ssandra-operator
